### ISSUE TITLE
Post/Term restriction issues

### ISSUE THREAD

**Issue by tannerm** [skillfulplugins/restrict-content-pro-buddypress#17]
If I use the Member Type Restriction option on a Post Type (Post, Page, etc), it does restrict properly, but it displays the Free Content Message from the RCP settings. On the other hand, if I use the Member Type Restriction option on a Taxonomy (Category, Tag, etc), it displays the Premium Content Message from the RCP settings. Shouldn't both of these restriction types show the same message?

Note: This may be happening because when you add a restriction to a Post Type (Post, Page, etc), it only shows the Member Access Option dropdown field, which defaults to Everyone. The only way to get the Member Type and Group restriction options to appear, is to choose Members of subscription level(s), Members with an access level, or Members with a certain role. So, even when I choose Members of subscription level(s), leave those subscription levels blank, and select a Member Type, it still saves the post with the default Everyone option, even though the required Member Type(s) are saved and listed there. Shouldn't there be dropdown options for Members with Member Type(s), and Members of Group(s)?

**Comment by samsmith89** [comment]
Closing as this is no longer an issue
