### ISSUE TITLE
Add better messaging for restricted content

### ISSUE THREAD

**Issue by tannerm** [skillfulplugins/restrict-content-pro-buddypress#18]
"Is there any way to get it to display a Restricted Content Message that's specific to the actual reason they are unable to access the content (Lack of the required Member Type/Group)? Possibly through a filter or something?"

**Comment by codelion7** [comment]
Here's an example function that filter's the restricted content message. You could duplicate this method and add your own conditionals to determine if the content is restricted by Member Type or Group:

https://github.com/restrictcontentpro/restrict-content-pro/blob/9c752e3119e84ca9cae946ba8d1ca642a398e20a/includes/content-filters.php#L202

**Comment by tannerm** [comment]
@codelion7 I've added a simple filter to handle this functionality for now. See an example here: https://docs.skillfulplugins.com/docs/rcp-buddypress/usage/custom-restriction-message/.
