### ISSUE TITLE
Remove BuddyPress admin bar

### ISSUE THREAD

**Issue by tannerm** [skillfulplugins/restrict-content-pro-buddypress#3]
BuddyPress maintains a bit of control over when they show the admin bar. If the a user decides to remove the admin bar, it would be a good idea to apply this to BuddyPress as well. See https://github.com/restrictcontentpro/restrict-content-pro/pull/993

**Comment by MikeNGarrett** [comment]
Thanks for moving it over. :-)

**Comment by tannerm** [comment]
@MikeNGarrett Sorry this has taken so long to implement! Can you tell me how I can replicate the issue that you are seeing?

**Comment by MikeNGarrett** [comment]
This was a bit ago, so my memory might be rusty. There's an option in RCP that hides the admin bar. The original request was to hide the buddypress admin bar when this option was selected. 
Here's the PR: 
https://github.com/restrictcontentpro/restrict-content-pro/pull/993/commits/cb71fb25453501a6398ce6b81b16c879dc5bdbe8

**Comment by tannerm** [comment]
Thanks @MikeNGarrett. I checked that issue and tried to duplicate but was unable to. Could it have been an issue caused by a theme or plugin you were using? Or perhaps the issue has already been resolved by BuddyPress.

**Comment by MikeNGarrett** [comment]
There's a possibility that BuddyPress updated to remove their admin bar when the WordPress admin bar was removed. I'm not sure. The way I understood it at the time was BuddyPress required you to remove a separate action for their additions to the admin bar for the bar to be completely removed. `remove_action( 'init', 'bp_core_load_admin_bar', 9 );`

**Comment by tannerm** [comment]
Gotcha. I'm going to close for and see if this pops up again.

Thanks Mike!
